[package]
name = "rust-digit-recognizer"
version = "0.1.0"
authors = ["Kevin McFarlane <kevin.mcfarlane@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple-stopwatch="0.1.4"
